<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Twitter Clone</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->tag->stylesheetLink("css/bootstrap.css"); ?>
        <?php echo $this->tag->stylesheetLink("css/bootstrap-theme.css"); ?>
        <?php echo $this->tag->stylesheetLink("css/bootstrap.min.css"); ?>
        <?php echo $this->tag->stylesheetLink("css/bootstrap-theme.min.css"); ?>
        <?php echo $this->tag->stylesheetLink("css/twitterClone.css"); ?>
    </head>

    <body>
        <?php echo $this->getContent(); ?>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <?php echo $this->tag->javascriptInclude("js/bootstrap.js", false); ?>
        <?php echo $this->tag->javascriptInclude("js/bootstrap.min.js", false); ?>
        <?php echo $this->tag->javascriptInclude("js/npm.js", false); ?>
      <?php echo $this->tag->javascriptInclude("js/function.js", false); ?>
    </body>
</html>	
